//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCaseStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketCancel
    {
        public string Cid { get; set; }
        public int ticketno { get; set; }
        public System.DateTime DepartureDate { get; set; }
    
        public virtual CustomerTable CustomerTable { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
